<?php  

header("Access-Control-Allow-Origin: *");
header("Content-Type: application/json; charset=UTF-8");


$norm=$_GET['norm'];
$tgllahir=$_GET['tgllahir'];
 

include 'config.php';


 
$sql = "SELECT PASIENRAWATINAP.PRWIKD_PASIEN as [RM]  ,
PASIEN.NAMAPASIEN, PASIEN.TGL_LAHIR ,
PASIENRAWATINAP.PRWIKD_DOKTER ,
DOKTER.FMDDOKTERN as [DPJP],
PASIENRAWATINAP.PRWIKD_POSISI ,
KAMAR.FMKKAMARINDUK, 
KAMAR_INDUK.FMKAMARN  ,
KAMAR.FMKNAMA_KAMAR,
PASIENRAWATINAP.PRWINO_TRANSAKSI,
PASIEN.KD_ASURANSI,
KELOMPOKCUSTOMER.FMKCUSTN ,
PASIEN.ALAMAT
,DATEDIFF(YEAR,[TGL_LAHIR], GETDATE()) UMUR  , CASE WHEN DATEDIFF(YEAR,[TGL_LAHIR], GETDATE()) BETWEEN 0 AND 1 THEN 'BY' WHEN DATEDIFF(YEAR,[TGL_LAHIR], GETDATE()) BETWEEN 2 AND 15 THEN 'AN' WHEN DATEDIFF(YEAR,[TGL_LAHIR], GETDATE()) BETWEEN 16 AND 30 THEN 'SDR' WHEN DATEDIFF(YEAR,[TGL_LAHIR], GETDATE()) BETWEEN 31 AND 100 AND JENIS_KELAMIN= 1 THEN 'TN' WHEN DATEDIFF(YEAR,[TGL_LAHIR], GETDATE()) BETWEEN 31 AND 100 AND JENIS_KELAMIN= 2 THEN 'NY' end as PANGGIL,KELOMPOKCUSTOMER.FMKJENIS_TARIP,JENIS_KELAMIN
 from pasienrawatinap, pasien, kamar, kamar_induk, DOKTER, KELOMPOKCUSTOMER 
 where pasienrawatinap.prwikd_pasien = pasien.kd_pasien
  and pasienrawatinap.PRWIKD_POSISI = KAMAR.FMKKAMAR_ID
   and KAMAR.FMKKAMARINDUK = KAMAR_INDUK.FMKAMAR_ID 
   and PASIEN.KD_ASURANSI = KELOMPOKCUSTOMER.FMKCUST_ID 
   and PASIENRAWATINAP.PRWIKD_DOKTER = DOKTER.FMDDOKTER_ID 
   and PASIENRAWATINAP.PRWIKD_PASIEN ='$norm' and PASIEN.TGL_LAHIR='$tgllahir'
    and pasienrawatinap.PRWITGL_KELUAR is null  order by KAMAR_INDUK.FMKAMARN, KAMAR.FMKNAMA_KAMAR";

$result = sqlsrv_query( $conn, $sql );

$response=array();
 while($row = sqlsrv_fetch_array($result, SQLSRV_FETCH_ASSOC))
 { 
 
$response[]=$row;
}

$data = json_encode($response);
 
echo ($data);
 
sqlsrv_close( $conn);
?>